# fly.toml app configuration file generated for dukarmo on 2025-07-22T11:40:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dukarmo"
primary_region = "bog"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false 
  auto_start_machines = true
  min_machines_running = 1  
  processes = ["app"]
